# Create All Rings

Product.create(product_name:'Black Opal', image_path:'/black_opal', product_type:'ring', price:250 ,in_stock: true)
Product.create(product_name:'Two Gold Band', image_path:'/gold_band_set_of_2', product_type:'ring', price:100, in_stock: true)
Product.create(product_name:'Gold Peridot', image_path:'/gold_bezel_peridot', product_type:'ring', price:150, in_stock: true)
Product.create(product_name:'Gold Diamond Alexandrite', image_path:'/gold_diamonds_alexandrite', product_type:'ring', price:200, in_stock: true)
Product.create(product_name:'Gold Diamond Opal', image_path:'/gold_diamond_opal', product_type:'ring', price:275, in_stock: true)
Product.create(product_name:'Gold Hexagon Alexandrite', image_path:'/gold_hexagon_alexandrite', product_type:'ring', price:220, in_stock: true)
Product.create(product_name:'Gold Leaf Ruby', image_path:'/gold_leaf_ruby', product_type:'ring', price:300, in_stock: true)
Product.create(product_name:'Gold Sapphire Emerald', image_path:'/gold_sapphire_emerald', product_type:'ring', price:233, in_stock: true)
Product.create(product_name:'Gold Round Alexandrite', image_path:'/gold_round_alexandrite', product_type:'ring', price:175, in_stock: true)
Product.create(product_name:'Gold Ruby', image_path:'/gold_ruby', product_type:'ring', price:275, in_stock: true)
Product.create(product_name:'Rose Gold Diamond Moss Agate', image_path:'/kite_mossAgate2', product_type:'ring', price:350, in_stock: true)
Product.create(product_name:'Rose Gold Kite Moss Agate', image_path:'/rose_gold_kite_mossAgate', product_type:'ring', price:320, in_stock: true)
Product.create(product_name:'Sterling Austrailian Opal', image_path:'/sterling_australian_opal', product_type:'ring', price:200, in_stock: true)
Product.create(product_name:'Two Sterling Bands', image_path:'/sterling_band_set_of_2', product_type:'ring', price:100, in_stock: true)
Product.create(product_name:'Sterling Diamond Sapphire', image_path:'/sterling_diamond&_sapphire_band', product_type:'ring', price:235, in_stock: true)
Product.create(product_name:'Sterling Flower Diamond', image_path:'/sterling_flower_diamond', product_type:'ring', price:70, in_stock: true)
Product.create(product_name:'Sterling Moss Agate', image_path:'/sterling_mossAgate', product_type:'ring', price:143, in_stock: true)
Product.create(product_name:'Sterling Diamond Sapphire Inlay', image_path:'/sterling_saphire&_diamond_inlay', product_type:'ring', price:175, in_stock: true)
Product.create(product_name:'Sterling Star Diamond', image_path:'/sterling_star_diamond', product_type:'ring', price:150, in_stock: true)
Product.create(product_name:'Sterling Wave Engraving', image_path:'/sterling_wave_engraving', product_type:'ring', price:50, in_stock: true)
Product.create(product_name:'Turtle Set Of Two', image_path:'/turtle_set_of_2', product_type:'ring', price:50, in_stock: true)
Product.create(product_name:'White Gold Diamond Ruby 3 Piece', image_path:'/white_gold_3piece_diamond&_ruby', product_type:'ring', price:175, in_stock: true)
Product.create(product_name:'White Gold Diamond Teal-Green Sapphire', image_path:'/white_gold_diamond_tealGreen_sapphire', product_type:'ring', price:247, in_stock: true)
Product.create(product_name:'White Gold Fire Opal', image_path:'/white_gold_fire_opal', product_type:'ring', price:300, in_stock: true)
Product.create(product_name:'White Gold Prong Emerald', image_path:'/white_gold_prong_emerald', product_type:'ring', price:300, in_stock: true)

#Create All Necklaces
Product.create(product_name:'Black Opal and Diamond Pendant', image_path:'/opal_diamond', product_type:'necklace', price:300, in_stock: true)
Product.create(product_name:'Amethyst Pendant', image_path:'/amethyst_pendant', product_type:'necklace', price: 500 , in_stock: true)
Product.create(product_name:'Sterling Silver Chain with an Emerald and Diamond Teardrop', image_path:'/emerald_diamond_teardrop', product_type:'necklace', price: 1500, in_stock: true)
Product.create(product_name:'Sterling Siver with Cube Emerald in Diamond', image_path:'/emrald_cube_pendant', product_type:'necklace', price: 1200, in_stock: true)
Product.create(product_name:'Gemstone Necklace', image_path:'/gemstones', product_type:'necklace', price: 300, in_stock: true)
Product.create(product_name:'Stackable Gold Chains', image_path:'/gold_3_stack', product_type:'necklace', price: 400, in_stock: true)
Product.create(product_name:'Gold Chain with Australian Opal', image_path:'/gold_australian_opal_iShape', product_type:'necklace', price: 1000 , in_stock: true)
Product.create(product_name:'Gold Bead Necklace', image_path:'/gold_beaded', product_type:'necklace', price: 300, in_stock: true)
Product.create(product_name:'Gold Chain with Raw Amethyst', image_path:'/gold_chain_amethyst_raw', product_type:'necklace', price: 1100, in_stock: true)
Product.create(product_name:'Gold Chain with Gold Ring', image_path:'/gold_chain_gold_ring', product_type:'necklace', price: 200, in_stock: true)
Product.create(product_name:'Gold Plated Necklace with Emerald and Diamond Teardrop', image_path:'/gold_emerald_teardrop', product_type:'necklace', price: 1700, in_stock: true)
Product.create(product_name:'Golden Flower', image_path:'/gold_flower', product_type:'necklace', price: 100, in_stock: true)
Product.create(product_name:'Bronze Chain with Round Gold Feature', image_path:'/gold_round_pendant', product_type:'necklace', price: 150, in_stock: true)
Product.create(product_name:'Gold Chain', image_path:'/gold-necklace', product_type:'necklace', price: 100, in_stock: true)
Product.create(product_name:'Three Layer Pearl Necklace', image_path:'/pearl_3_stack', product_type:'necklace', price: 1200, in_stock: true)
Product.create(product_name:'Rose Quartz Crystal', image_path:'/rose_quartz_crystal_2', product_type:'necklace', price: 75, in_stock: true)
Product.create(product_name:'Sterling Silver Chain with Rose Quartz Crystal', image_path:'/sterling_rose_quartz_crystal', product_type:'necklace', price: 90, in_stock: true)
Product.create(product_name:'Sterling Silver Chain with Ruby Beads', image_path:'/ruby_beads_pendant_raw', product_type:'necklace', price: 1150, in_stock: true)
Product.create(product_name:'Sterling Silver Chain with Ruby and Diamond Pendant', image_path:'/ruby_diamond_teardrop', product_type:'necklace', price: 1500, in_stock: true)
Product.create(product_name:'Sterling Silver Chain with Ruby Flower', image_path:'/ruby_flower', product_type:'necklace', price: 500, in_stock: true)
Product.create(product_name:'Sterling Sliver Chain with Smokey Quartz Crystal', image_path:'/smokey_quartz_crystal', product_type:'necklace', price: 90, in_stock: true)
Product.create(product_name:'Sterling Silver Chain with Amethyst', image_path:'/sterling_amethyst', product_type:'necklace', price: 1300, in_stock: true)
Product.create(product_name:'White Gold Chain with Diamond Pendant', image_path:'/white_gold_diamond_Yshape', product_type:'necklace', price: 2000 , in_stock: true)

#Create All Earrings
Product.create(product_name:'Amethyst and Garnet Ship Sails Encrusted with Diamonds | Drop', image_path:'/amethyst_garnet_shipSail_drop', product_type:'earring', price:2000, in_stock: true)
Product.create(product_name:'Amethyst Earrings | Stud', image_path:'/amethyst_stud', product_type:'earring', price:1100, in_stock: true)
Product.create(product_name:'Floating Butterfly | Hoop', image_path:'/butterfly_double_hoop', product_type:'earring', price:750, in_stock: true)
Product.create(product_name:'Infinity Diamond | Stud', image_path:'/diamond_infinity_stud', product_type:'earring', price:1250, in_stock: true)
Product.create(product_name:'Gold Hoop Wrapped with Diamond | Hoop', image_path:'/wrapped_diamond_hoop', product_type:'earring', price:1500, in_stock: true)
Product.create(product_name:'Duck Earrings | Drop', image_path:'/duck', product_type:'earring', price:20, in_stock: true)
Product.create(product_name:'Emerald and Diamonds | Dangle', image_path:'/emerald_diamond_drop', product_type:'earring', price:2000, in_stock: true)
Product.create(product_name:'Emerald Teardrops | Drop', image_path:'/emerald_drop', product_type:'earring', price:2100, in_stock: true)
Product.create(product_name:'Gold Horseshoe with Diamonds | Stud', image_path:'/gold_diamond_horseshoe_stud', product_type:'earring', price: 950, in_stock: true)
Product.create(product_name:'Gold Leaf with Emerald and Diamond | Drop', image_path:'/gold_emerald_leaf_drop', product_type:'earring', price:1200, in_stock: true)
Product.create(product_name:'Gold Hoops | Hoop', image_path:'/gold_hoop', product_type:'earring', price:1000, in_stock: true)
Product.create(product_name:'Gold and Pearl | Hoop', image_path:'/gold_pearl_hoop', product_type:'earring', price:1400, in_stock: true)
Product.create(product_name:'Platinum Intertwined with Diamond and Gold | Hoop', image_path:'/gold_platinum_diamond_hoop', product_type:'earring', price:3200, in_stock: true)
Product.create(product_name:'Moons and Stars | Dangle', image_path:'/moon_and_star_drop', product_type:'earring', price:100, in_stock: true)
Product.create(product_name:'Pearl with Diamond Loop | Drop', image_path:'/pearl_diamond_dangle', product_type:'earring', price: 2200, in_stock: true)
Product.create(product_name:'Pearl Earrings | Drop', image_path:'/pearl_drop', product_type:'earring', price:1800, in_stock: true)
Product.create(product_name:'Pearl Studs | Stud', image_path:'/pearl_stud', product_type:'earring', price: 1000, in_stock: true)
Product.create(product_name:'Ruby Teardrop | Dangle', image_path:'/ruby_teardrop_drop', product_type:'earring', price:2500, in_stock: true)
Product.create(product_name:'Sapphire Flower | Stud', image_path:'/sapphire_flower_stud', product_type:'earring', price:2700, in_stock: true)
Product.create(product_name:'Silver Hoops | Hoop', image_path:'/silver_hoop', product_type:'earring', price:1000, in_stock: true)
Product.create(product_name:'Sterling Silver with Emerald | Drop', image_path:'/sterling_emerald_drop', product_type:'earring', price: 2000, in_stock: true)
Product.create(product_name:'Tagau Earrings | Dangle', image_path:'/tagau_stack', product_type:'earring', price:1000, in_stock: true)
Product.create(product_name:'White Gold Aquamarine with Diamond Cluster | Stud', image_path:'/white_gold_aquamarine_diamond_cluster', product_type:'earring', price: 2300, in_stock: true)
Product.create(product_name:'White Gold Diamond Infinty | Dangle', image_path:'/white_gold_diamond_8Shape_dangle', product_type:'earring', price: 2000, in_stock: true)